### ISSUE TITLE
issue with deploying to heroku

### ISSUE THREAD

**Issue by atherdon** [strongloop/strong-error-handler#70]
# Description/Steps to reproduce
i'm running an app and get an issue:
```
Error: Cannot find module 'http-status'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/strong-error-handler/lib/data-builder.js:9:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/strong-error-handler/lib/handler.js:11:25)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```
and everything works fine on local machine

**Note** i figure it out, but maybe it'll be helpful for you - it works well with node v.9.4.0 and crashing when i use node v.8.1.4

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by bajtos** [comment]
> Note i figure it out, but maybe it'll be helpful for you - it works well with node v.9.4.0 and crashing when i use node v.8.1.4

Closing this issue as resolved then. Node.js 8.x is no longer supported by the project.
