### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by dkrantsberg** [strongloop/strong-error-handler#84]
# Description
I have enabled debug error output in my LoopBack 4 application by setting RestBindings.ERROR_WRITER_OPTIONS. 
After this some errors resulted in no output at all. Just 500 response with zero content. 

After some digging I've found that JSON.stringify was failing on circular references and it was taking the entire node process down.  Thanks to pm2 it was automatically restarting. 

Here's the error stack:

```
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at sendJson (/labshare/storage-api/node_modules/strong-error-handler/lib/send-json.js:9:22)
    at Function.writeErrorToResponse (/labshare/storage-api/node_modules/strong-error-handler/lib/handler.js:69:3)
    at RejectProvider.action (/labshare/storage-api/node_modules/@loopback/rest/src/providers/reject.provider.ts:41:5)
    at MySequence.reject (/labshare/storage-api/node_modules/@loopback/rest/src/providers/reject.provider.ts:27:37)
    at MySequence.handle (/labshare/storage-api/src/sequence.ts:84:12)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

I'm going to make a PR to fix this.

**Comment by dhmlau** [comment]
Closing as done as PR #85 has landed. Thanks @dkrantsberg for your contribution!
